jenkins:
  systemMessage: "Welcome to the demo setup for Jenkins Configuration as Code plugin. For more information look in the official repo with our demo setup: https://github.com/Praqma/praqma-jenkins-casc"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: demoAdmin
         password: ${adminpw}
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - name: "anonymous"
          permissions:
           - "Overall/Read"
           - "Job/Read"
           - "View/Read"
        - name: "authenticated"
          permissions:
           - "Overall/Administer"
#  nodes:
#    - dumb:
#        labelString: "build jnlp"
#        mode: NORMAL
#        name: "build-agent-jnlp"
#        remoteFS: "/home/agent/ws" 
#        launcher:
#          jnlp:
#            workDirSettings:
#              disabled: true
#              workDirPath: 
#              internalDir:
#              failIfWorkDirIsMissing: false
#    - dumb:
#        labelString: "build ssh"
#        mode: NORMAL
#        name: "build-agent-ssh"
#        remoteFS: "/home/agent/ws" 
#        launcher:
#          SSHLauncher:
#            host: "localhost"
#            port: 22
#            credentialsId: agent-private-key
#            launchTimeoutSeconds: 20
#            maxNumRetries: 2
#            retryWaitTime: 15
#            sshHostKeyVerificationStrategy:
#              manuallyTrustedKeyVerificationStrategy:
#                requireInitialManualTrust: false
  globalLibraries:
    libraries:
      - name: "demo-lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/Praqma/praqma-jenkins-casc-shared-lib-demo"
      - name: "jenkins-infra"
        implicit: true
        defaultVersion: "master"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/jenkins-infra/pipeline-library"

  warnings:
    parsers:
      - name: "Example parser"
        linkName: "Example parser link"
        trendName: "Example parser trend name"
        regexp: "^\\s*(.*):(\\d+):(.*):\\s*(.*)$"
        script: |
          import hudson.plugins.warnings.parser.Warning
          String fileName = matcher.group(1)
          String lineNumber = matcher.group(2)
          String category = matcher.group(3)
          String message = matcher.group(4)
          return new Warning(fileName, Integer.parseInt(lineNumber), "Dynamic Parser", category, message);
        example: "somefile.txt:2:SeriousWarnings:SomethingWentWrong"           

credentials:
  system:
    ? # "global"
    : - usernamePassword:
          scope:    SYSTEM
          id:       github-user
          username: ReleasePraqma
          password: ${github}
      - basicSSHUserPrivateKey:
          scope: SYSTEM
          id: agent-private-key
          username: agentuser
          passphrase: 
          description: "ssh private key used to connect ssh slaves"
          privateKeySource:
            directEntry:
              privateKey: ${agent_private_key}
jobs:
  - >
      multibranchPipelineJob('demo1-example') {
        description("Example job that uses and configures the warnings plugin and makes use of a global library")
        branchSources {
          git {
            remote('https://github.com/Praqma/praqma-jenkins-casc-demo1-example')
          }
        }
      }
  - > 
      multibranchPipelineJob('Configuration as Code plugin') {
        description("Building the configuration as code plugin from jenkins-ci.org")
        branchSources {
          git {
            remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
          }
        }
      }

tool:
  git:
    installations:
      - name: mvn
        home: "mvn" 
