jenkins:
  systemMessage: "Welcome to the demo setup for Jenkins Configuration as Code plugin"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: demoAdmin
         password: ${adminpw}
       - id: test
         password: test
  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - name: "anonymous"
          permissions:
           - "Overall/Read"
        - name: "authenticated"
          permissions:
           - "Overall/Administer"                            
credentials:
  system:
    ? # "global"
    : - usernamePassword:
          scope:    SYSTEM
          id:       github-user
          username: ReleasePraqma
          password: ${github}
jobs:
  - >
      multibranchPipelineJob('demo1-example') {
        branchSources {
          git {
            remote('https://github.com/Praqma/praqma-jenkins-casc-demo1-example')
          }
        }
      }
  - > 
      multibranchPipelineJob('demo2-example') {
        branchSources {
          git {
            remote('https://github.com/Praqma/praqma-jenkins-casc-demo1-example')
          }
        }
      }